import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import Navbar from "@/components/Navbar";
import ProfilePic from "@/components/ProfilePic";

export const metadata = {
  title: "Next Js Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-800 ${inter.className}`}>
        <Navbar />
        <ProfilePic />
        {children}
      </body>
    </html>
  );
}
